import type { Metadata } from 'next';
import ContextProvider from '@/components/ContextProvider/ContextProvider';
import { ReduxProvider } from './ReduxProvider';
import ErrorButton from '@/components/ErrorButton/ErrorButton';
import Search from '@/components/Search/Search';
import ThemeControls from '@/components/ThemeControls/ThemeControls';
import Controls from '@/components/Controls/Controls';
import { FC } from 'react';
import Head from 'next/head';

import styles from './searchView.module.css';
import './index.css';

export const metadata: Metadata = {
  title: 'StarWars API',
};

type Props = {
  children?: React.ReactNode;
  details: React.ReactNode;
};

const RootLayout: FC<Props> = ({ children, details }) => {
  return (
    <html lang="en">
      <Head>
        <title>StarWars API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <ReduxProvider>
          <ContextProvider>
            <div className={'view'}>
              <div className={styles.header}>
                <div className="container">
                  <div className={styles.wrapper}>
                    <ErrorButton />
                    <Search />
                    <ThemeControls />
                  </div>
                </div>
              </div>

              <div className="container">
                <div className={styles.content}>
                  {children}
                  {details}
                </div>
              </div>

              <Controls />
            </div>
          </ContextProvider>
        </ReduxProvider>
      </body>
    </html>
  );
};

export default RootLayout;
