import { HOME_PAGE } from '@/helpers/constants';
import Head from 'next/head';

export async function getServerSideProps() {
  return {
    redirect: {
      destination: HOME_PAGE,
      permanent: true,
    },
  };
}

export default function Home() {
  return (
    <>
      <Head>
        <title>StarWars API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
